name: Terraform K8s

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Executar terraform destroy?'
        required: true
        default: 'false'
        type: choice
        options: ['true', 'false']

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_datadog_app_key: ${{ secrets.TF_VAR_DATADOG_APP_KEY }}
      TF_VAR_app_image_tag:   ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.destroy != 'true'
        run: terraform plan -out=tfplan.tfout

      - name: Terraform Apply
        if: github.event.inputs.destroy != 'true'
        run: terraform apply --auto-approve tfplan.tfout

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy --auto-approve
